#!/usr/bin/env python3
"""A hack or translation of a set as an .mra, from the MAME set's .mra.

    tools/ns2_patch_mra.py [--zip ZIP] [--credit TEXT] SET DIR NAME OUT
      SET   the MAME set it modifies
      DIR   the modified set's ROM files (loose, MAME's file names)
      NAME  the .mra's <name>
      OUT   the .mra to write
      --zip ZIP  load the modified files from ZIP (the user's pre-patched zip)
                 instead of patching: see below
      --credit TEXT  a line in the .mra's header comment crediting the
                 modification's authors (its source, a URL); no '--' in it

With --zip, the changed files' parts name their modified CRCs, ZIP is the
first of the .mra's zips (MAME's set zips follow, for the files the
modification leaves alone), and <setname> is ZIP's stem; no ROM data is
written. Without it:

The set's own .mra (tools/ns2_mra.py) is written again with NAME, and every
byte where the image built from DIR's files differs from the image built from
MAME's is a <patch> in the ROM download, which MiSTer's loader applies to the
assembled image. A file in DIR replaces MAME's file of the same name; files
equal to MAME's, and files the set does not load, change nothing. The result
is checked by assembling it as ns2_mra --check does and comparing it with the
image built from DIR. No ROM data but the patched bytes is written.
"""
import os, re, sys
CREDIT = None  # --credit's text


def credit_line():
    return f'  Credit: {CREDIT}\n' if CREDIT else ''
import xml.etree.ElementTree as ET
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import ns2_romdata as R
import ns2_mra as M

GAP = 8        # patches closer than this are one patch (fewer, longer lines)
LINE = 32      # bytes a <patch> at most


def image_with(name, repl, sets, gm):
    """The set's image with some ROM files' bytes replaced (by file name)."""
    get = R.Files.get
    def patched(self, fn, crc):
        return repl[fn.lower()] if fn.lower() in repl else get(self, fn, crc)
    R.Files.get = patched
    try:
        return R.build(name, sets, gm)[1]
    finally:
        R.Files.get = get


def runs(a, b):
    out, i, n = [], 0, len(a)
    while i < n:
        if a[i] == b[i]:
            i += 1
            continue
        j = i
        last = i
        while j < n and j - last <= GAP:
            if a[j] != b[j]:
                last = j
            j += 1
        out.append((i, bytes(b[i:last + 1])))
        i = last + 1
    return out


def write_zip_mra(name, title, out, text, repl, changed, mod, zipname, sets, gm):
    """The .mra that loads the changed files from the user's pre-patched zip."""
    import tempfile, zipfile, zlib
    stem = os.path.splitext(zipname)[0]
    for f in changed:
        crc = zlib.crc32(repl[f]) & 0xffffffff
        text, n = re.subn(r'<part crc="[0-9a-f]{8}" name="%s"' % re.escape(f),
                          f'<part crc="{crc:08x}" name="{f}"', text)
        if not n:
            raise SystemExit(f'{f}: no part in the .mra')
    text = re.sub(r'<setname>[^<]*</setname>', f'<setname>{stem}</setname>', text, count=1)
    text = re.sub(r'(<rom index="0" zip=")', r'\g<1>' + zipname + '|', text, count=1)
    head = (f'  {title}: MAME\'s {name} ({gm[name]["desc"]}) with {", ".join(changed)}\n'
            f'  from {zipname}, the modified set\'s zip, which the user makes (MAME\'s {name}\n'
            f'  zips give the files it leaves alone). Generated by tools/ns2_patch_mra.py\n'
            f'  (its zip mode) on tools/ns2_mra.py\'s {name} .mra; do not hand-edit.\n' + credit_line())
    text = re.sub(r'<!--\n.*?Generated by tools/ns2_mra.py[^\n]*\n', lambda m: '<!--\n' + head, text, count=1, flags=re.S)
    ET.fromstring(text)
    # the check: assemble it from a zip of DIR's changed files and MAME's zips
    with tempfile.TemporaryDirectory() as d:
        with zipfile.ZipFile(os.path.join(d, zipname), 'w') as zf:
            for f in changed:
                zf.writestr(f, repl[f])
        for z in os.listdir(R.ROMS):
            if z.endswith('.zip') and z != zipname:
                os.symlink(os.path.join(os.path.abspath(R.ROMS), z), os.path.join(d, z))
        roms, R.ROMS = R.ROMS, d
        try:
            img = M.downloaded(M.assemble(text, name, gm), name, sets, gm)
        finally:
            R.ROMS = roms
    if img != mod:
        raise SystemExit(f'the .mra does not assemble to the modified image')
    os.makedirs(os.path.dirname(os.path.abspath(out)), exist_ok=True)
    open(out, 'w').write(text)
    print(f'{out}: {", ".join(changed)} from {zipname}; assembles equal')


def main():
    args = sys.argv[1:]
    global CREDIT
    zipname = None
    while args[:1] in (['--zip'], ['--credit']) and len(args) > 1:
        if args[0] == '--zip':
            zipname = args[1]
        else:
            CREDIT = args[1]
            if '--' in CREDIT:
                raise SystemExit("--credit: an XML comment cannot hold '--'")
        args = args[2:]
    if len(args) != 4:
        raise SystemExit(__doc__)
    name, src, title, out = args
    sets, gm = R.parse(), R.games()
    stock_regions, stock = R.build(name, sets, gm)
    repl = {}
    for fn in sorted(os.listdir(src)):
        p = os.path.join(src, fn)
        if os.path.isfile(p) and not fn.lower().endswith('.zip'):
            repl[fn.lower()] = open(p, 'rb').read()
    mod = image_with(name, repl, sets, gm)
    patches = runs(stock, mod)
    if not patches:
        raise SystemExit(f'{src}: no byte differs from {name}')

    text, _ = M.mra_text(name, sets, gm)
    text = re.sub(r'<name>[^<]*</name>', f'<name>{title}</name>', text, count=1)
    changed = sorted(f for f in repl if any(l.get('file', '').lower() == f for r in sets[name] for l in r['loads'])
                     and repl[f] != R.Files(R.zip_chain(name, gm)).by_name.get(f))
    if zipname:
        return write_zip_mra(name, title, out, text, repl, changed, mod, zipname, sets, gm)
    head = (f'  {title}: MAME\'s {name} ({gm[name]["desc"]}) with {", ".join(changed)} replaced,\n'
            f'  as {len(patches)} runs ({sum(len(d) for _, d in patches)} bytes) of <patch> after the parts:\n'
            f'  only MAME\'s {name} zips are needed. Generated by tools/ns2_patch_mra.py\n'
            f'  on tools/ns2_mra.py\'s {name} .mra; do not hand-edit.\n' + credit_line())
    text = re.sub(r'<!--\n.*?Generated by tools/ns2_mra.py[^\n]*\n', lambda m: '<!--\n' + head, text, count=1, flags=re.S)
    # one line each (MiSTer parses a patch's text as spaced hex), LINE bytes at most
    L = []
    for off, d in patches:
        for k in range(0, len(d), LINE):
            L.append(f'    <patch offset="0x{off + k:07X}">{d[k:k + LINE].hex(" ").upper()}</patch>')
    text = text.replace('  </rom>', '\n'.join(L) + '\n  </rom>', 1)
    ET.fromstring(text)
    if M.downloaded(M.assemble(text, name, gm), name, sets, gm) != mod:
        raise SystemExit('the patched .mra does not assemble to the modified image')
    os.makedirs(os.path.dirname(os.path.abspath(out)), exist_ok=True)
    open(out, 'w').write(text)
    print(f'{out}: {len(patches)} patches, {sum(len(d) for _, d in patches)} bytes; assembles equal')


if __name__ == '__main__':
    main()
