#!/usr/bin/env python3
"""The sound chips' interpolators' coefficients (NS2-26, NS2-29):

    tools/ns2_firgen.py c140 > rtl/ns2_c140_fir_coef.vh
    tools/ns2_firgen.py ym   > rtl/ns2_ym_fir_coef.vh
    tools/ns2_firgen.py check    (each filter's response against MAME's)

rtl/ns2_fir4.sv interpolates a chip's samples 4x through a 128-tap
low-pass (32 taps a phase), so that a held sample puts no images above the
chip's Nyquist: the C140 at 21.333 kHz (clk_sys / 2304), the YM2151 at
55.93 kHz (jt51, 3.579545 MHz / 64).

The passband is MAME's own response. MAME 0.289's default resampler
(audio_resampler_lofi, emu/resampler.cpp) averages m_source_divide samples
when the source is faster than its 48 kHz output (the YM2151: pairs, to
27.97 kHz), then interpolates with a 4-point cubic: the YM2151 is -3.3 dB
at 9.5 kHz and -15 dB at 16 kHz in MAME, the C140 -4.9 dB at 9.5 kHz. Above
the passband the filter stops (MAME's leftover images and the aliasing of
its averaging are not copied):
  - C140: MAME's curve to 9.8 kHz (within 0.1 dB to 9.5 kHz), -8.6 dB at 10
    kHz, -34 dB at 11 kHz, -51 dB at 11.3 kHz, below -84 dB from 12 kHz.
  - YM2151: MAME's curve to 26.3 kHz (within 0.1 dB to 23 kHz, where it is
    -52 dB), below -100 dB from 27.97 kHz.
A weighted least-squares fit (stopband weight 300), linear phase, the DC
gain exactly one; s18 coefficients with each phase's sum about 2^17.
"""
import sys
import numpy as np

L, N, Q = 4, 128, 17
FILTERS = {
    # name: (input rate, passband edge, stopband edge, function name)
    'c140': (49152000 / 2304, 9800.0, 11500.0, 'coef_c140'),
    'ym':   (3579545 / 64, 0.47 * 3579545 / 64, 0.5 * 3579545 / 64, 'coef_ym'),
}


# MAME's lofi resampler's interpolation functions (resampler.cpp)
def _f0(p):
    return (p - p ** 3) / 6


def _f1(p):
    p = np.asarray(p, float)
    lo = p + (p * p - p ** 3) / 2
    q = 1 - p
    hi = 1.0 + _f0(p) + _f0(q) - (q + (q * q - q ** 3) / 2)
    return np.where(p > 0.5, hi, lo)


def mame_response(f, fs, ft=48000):
    """|H(f)| of MAME's lofi resampler for a source at fs Hz."""
    div = 1 if fs <= ft else 1 + int(fs) // ft
    fd = fs / div
    x = np.linspace(-2, 2, 4001)
    d = np.abs(x)
    h = np.where(d < 1, _f1(1 - np.minimum(d, 1)), np.where(d < 2, -_f0(2 - np.minimum(d, 2)), 0.0))
    dx = x[1] - x[0]
    f = np.atleast_1d(np.asarray(f, float))
    H = np.abs(np.exp(-2j * np.pi * np.outer(f / fd, x)) @ h) * dx
    if div > 1:
        H *= np.abs(np.exp(-2j * np.pi * np.outer(f / fs, np.arange(div))).mean(axis=1))
    return H


def coefs(name):
    fs_in, f_pass, f_stop, _ = FILTERS[name]
    fs = fs_in * L
    fg = np.linspace(0, fs / 2, 6000)
    D = np.zeros_like(fg)
    W = np.zeros_like(fg)
    pb, sb = fg <= f_pass, fg >= f_stop
    D[pb] = mame_response(fg[pb], fs_in)
    W[pb], W[sb] = 1.0, 300.0
    k = np.arange(N // 2)
    A = 2 * np.cos(2 * np.pi * np.outer(fg / fs, k + 0.5))
    b = np.linalg.lstsq(A * W[:, None], D * W, rcond=None)[0]
    h = np.concatenate([b[::-1], b])
    h = h / h.sum() * L
    hq = np.round(h * (1 << Q)).astype(int)
    assert np.abs(hq).max() < (1 << 17)
    return hq


def response(hq, fs_in, f):
    n = np.arange(len(hq))
    f = np.atleast_1d(np.asarray(f, float))
    return np.abs(np.exp(-2j * np.pi * np.outer(f / (fs_in * L), n)) @ (hq / (1 << Q) / L))


def check():
    for name, (fs_in, _, _, _) in FILTERS.items():
        hq = coefs(name)
        print(f'{name}: phase sums {[int(hq[p::L].sum()) for p in range(L)]}, max |coef| {np.abs(hq).max()}')
        for f in (1e3, 4e3, 7.5e3, 9.5e3, 10.5e3, 13e3, 16e3, 20e3, 23e3, 0.5 * fs_in, 0.6 * fs_in, fs_in):
            got = 20 * np.log10(response(hq, fs_in, f)[0] + 1e-12)
            ref = '' if f > 0.5 * fs_in else f'  MAME {20 * np.log10(mame_response(f, fs_in)[0] + 1e-12):+6.1f}'
            print(f'  {f / 1000:6.2f} kHz  {got:+7.1f} dB{ref}')


def main():
    if len(sys.argv) < 2 or sys.argv[1] not in (*FILTERS, 'check'):
        sys.exit(__doc__)
    if sys.argv[1] == 'check':
        return check()
    name = sys.argv[1]
    fs_in, f_pass, f_stop, fn = FILTERS[name]
    hq = coefs(name)
    print(f'// Generated by tools/ns2_firgen.py {name}; do not hand-edit. The interpolator')
    print(f'// of a {fs_in:.1f} Hz chip (rtl/ns2_fir4.sv): {N} taps, x{L}, MAME\'s lofi resampler\'s')
    print(f'// response to {f_pass:.0f} Hz, stopband from {f_stop:.0f} Hz, s18.')
    print(f'// {fn}(i) is tap i; phase p, tap k is {fn}(4k + p).')
    print(f'function automatic signed [17:0] {fn}(input [6:0] i);')
    print('\tcase (i)')
    for i, v in enumerate(hq):
        print(f"\t\t7'd{i}: {fn} = {'-' if v < 0 else ''}18'sd{abs(v)};")
    print(f"\t\tdefault: {fn} = 18'sd0;")
    print('\tendcase')
    print('endfunction')


if __name__ == '__main__':
    main()
