#!/usr/bin/env python3
"""The C140's anti-imaging interpolator's coefficients (NS2-26):

    tools/ns2_firgen.py > rtl/ns2_c140_fir_coef.vh

The C140 runs at 21.333 kHz (clk_sys / 2304), and a held sample puts its
images above its 10.67 kHz Nyquist (+6 dB at 11 kHz to +24 dB at 18 kHz
against MAME, whose resampler removes them). rtl/ns2_c140_fir.sv
interpolates 4x to 85.333 kHz through this low-pass: 128 taps (32 a
phase), a Kaiser-windowed sinc, cutoff 10.2 kHz, beta 6: flat to 9 kHz
(0.0 dB), -3.8 dB at 10 kHz, -42 dB at 11.3 kHz, -66 dB at 12 kHz and
below -75 dB from 14 kHz. The coefficients are s18 with a phase's sum
about 2^17 (unity gain).
"""
import numpy as np

FS_IN = 49152000 / 2304
L, N, FC, BETA, Q = 4, 128, 10200.0, 6.0, 17


def coefs():
    fs = FS_IN * L
    n = np.arange(N) - (N - 1) / 2
    h = 2 * FC / fs * np.sinc(2 * FC / fs * n) * np.kaiser(N, BETA)
    h = h / h.sum() * L
    hq = np.round(h * (1 << Q)).astype(int)
    assert np.abs(hq).max() < (1 << 17)
    return hq


def main():
    hq = coefs()
    print('// Generated by tools/ns2_firgen.py; do not hand-edit. The C140\'s')
    print(f'// interpolator (NS2-26): {N} taps, x{L}, cutoff {FC:.0f} Hz, Kaiser beta {BETA}, s18.')
    print('// coef(i) is tap i; phase p, tap k is coef(4k + p).')
    print('function automatic signed [17:0] coef(input [6:0] i);')
    print('\tcase (i)')
    for i, v in enumerate(hq):
        print(f"\t\t7'd{i}: coef = {'-' if v < 0 else ''}18'sd{abs(v)};")
    print("\t\tdefault: coef = 18'sd0;")
    print('\tendcase')
    print('endfunction')


if __name__ == '__main__':
    main()
